# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d1a013d73333f8d4b050a7850234677bafff07a939ac2fe4427e58a9b301503952063937cf8ed7af1431014e05f9887b61b91bca0e715362da84d8bf70d8bf

test:
  secret_key_base: ec416880e04bb936da6a6839777ff0404b9dbf00d42fe16489c187b4e0da25b5543295c4543a023f328dbc217866849bf1a419b7518f195b779a3bdd49824463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
